"""empty message

Revision ID: 0c1e847a182e
Revises: e800d9440b54
Create Date: 2023-05-25 17:17:05.962086

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0c1e847a182e'
down_revision = 'e800d9440b54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('option', sa.String(length=200), nullable=True))

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_column('option')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('option', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=200), nullable=True))

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('option')

    # ### end Alembic commands ###
