"""add individual code

Revision ID: 219ba7becb11
Revises: 98e3f06929e1
Create Date: 2023-04-19 17:27:08.155237

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '219ba7becb11'
down_revision = '98e3f06929e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('individual_code', sa.String(length=16), nullable=True))

    with op.batch_alter_table('user_address', schema=None) as batch_op:
        batch_op.drop_column('individual_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('individual_code', mysql.INTEGER(), autoincrement=False, nullable=False))

    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_column('individual_code')

    # ### end Alembic commands ###
