"""empty message

Revision ID: 3b164755a40f
Revises: 509d0badfdd0
Create Date: 2023-04-23 17:25:01.930338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b164755a40f'
down_revision = '509d0badfdd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint('payment_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'subscription', ['subscription_id'], ['id'])

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_constraint('subscription_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tariff', ['tariff_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'subscription', ['subscription_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('subscription_id')

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('subscription_ibfk_2', 'tariff', ['tariff_id'], ['id'], onupdate='RESTRICT', ondelete='CASCADE')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('payment_ibfk_2', 'subscription', ['subscription_id'], ['id'], onupdate='RESTRICT', ondelete='CASCADE')

    # ### end Alembic commands ###
