"""change address types

Revision ID: 48075a12cff7
Revises: 44bcc7d8435b
Create Date: 2023-04-16 14:55:48.642563

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '48075a12cff7'
down_revision = '44bcc7d8435b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.alter_column('house',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('building',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('front_door',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('apartment',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.alter_column('apartment',
               existing_type=sa.String(length=200),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('front_door',
               existing_type=sa.String(length=200),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('building',
               existing_type=sa.String(length=200),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('house',
               existing_type=sa.String(length=200),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
