"""test-1

Revision ID: 509d0badfdd0
Revises: 3c3b92e0fab3
Create Date: 2023-04-23 17:02:59.095167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '509d0badfdd0'
down_revision = '3c3b92e0fab3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'subscription', ['subscription_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('subscription_id')

    # ### end Alembic commands ###
