"""empty message

Revision ID: 55499ffe9e2a
Revises: 42e095556319
Create Date: 2023-04-21 15:51:18.072051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55499ffe9e2a'
down_revision = '42e095556319'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('payment_status')

    # ### end Alembic commands ###
