"""test

Revision ID: 73629ba71c5e
Revises: 468d4ea3f1c5
Create Date: 2023-04-23 16:44:15.801462

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '73629ba71c5e'
down_revision = '468d4ea3f1c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archive_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_sub', sa.Integer(), nullable=False))
        batch_op.drop_constraint('payment_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('payment_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tariff', ['tariff_id'], ['id'])
        batch_op.create_foreign_key(None, 'payment', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('payment_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_id', mysql.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('payment_ibfk_1', 'tariff', ['tariff_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('payment_ibfk_3', 'payment', ['user_id'], ['id'], onupdate='RESTRICT', ondelete='CASCADE')
        batch_op.drop_column('active_sub')

    op.drop_table('archive_payment')
    # ### end Alembic commands ###
