"""add address migrate

Revision ID: 7939c73cc271
Revises: d3a49b2c89b8
Create Date: 2023-04-16 14:21:46.046980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7939c73cc271'
down_revision = 'd3a49b2c89b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street', sa.String(length=2000), nullable=False),
    sa.Column('house', sa.Integer(), nullable=False),
    sa.Column('building', sa.Integer(), nullable=True),
    sa.Column('front_door', sa.Integer(), nullable=True),
    sa.Column('apartment', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('address')
    # ### end Alembic commands ###
