"""empty message

Revision ID: 85a1e6c0cede
Revises: a3dca033253e
Create Date: 2023-04-24 03:37:53.520442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85a1e6c0cede'
down_revision = 'a3dca033253e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'application_status', ['status'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
