"""equipment_list add 

Revision ID: 98e3f06929e1
Revises: b0907a848af7
Create Date: 2023-04-19 16:20:51.772521

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '98e3f06929e1'
down_revision = 'b0907a848af7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_column('building')

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'equipment_list', ['equipment_id'], ['id'])
        batch_op.drop_column('name')

    with op.batch_alter_table('user_address', schema=None) as batch_op:
        batch_op.drop_column('building')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('building', mysql.VARCHAR(collation='utf8mb4_general_ci', length=200), nullable=True))

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=1000), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('equipment_id')

    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('building', mysql.VARCHAR(collation='utf8mb4_general_ci', length=200), nullable=True))

    op.drop_table('equipment_list')
    # ### end Alembic commands ###
