"""empty message

Revision ID: a189acc73897
Revises: 3b164755a40f
Create Date: 2023-04-23 17:55:33.949812

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a189acc73897'
down_revision = '3b164755a40f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.alter_column('option',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=200),
               nullable=True)
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('option',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=200),
               nullable=False)

    # ### end Alembic commands ###
