"""empty message

Revision ID: ae1d6fd2c907
Revises: a189acc73897
Create Date: 2023-04-23 18:33:53.866498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae1d6fd2c907'
down_revision = 'a189acc73897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_constraint('address_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('address_ibfk_4', type_='foreignkey')
        batch_op.create_foreign_key(None, 'equipment', ['equipment_id'], ['id'])
        batch_op.create_foreign_key(None, 'tariff', ['tariff_id'], ['id'])

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('period', sa.Date(), nullable=False))
        batch_op.drop_constraint('payment_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'subscription', ['subscription_id'], ['id'])

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_constraint('subscription_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tariff', ['tariff_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_ibfk_7', type_='foreignkey')
        batch_op.create_foreign_key(None, 'subscription', ['subscription_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_ibfk_7', 'subscription', ['subscription_id'], ['id'], onupdate='RESTRICT', ondelete='SET NULL')

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('subscription_ibfk_2', 'tariff', ['tariff_id'], ['id'], onupdate='RESTRICT', ondelete='CASCADE')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('payment_ibfk_2', 'subscription', ['subscription_id'], ['id'], onupdate='RESTRICT', ondelete='CASCADE')
        batch_op.drop_column('period')

    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('address_ibfk_4', 'tariff', ['tariff_id'], ['id'], onupdate='RESTRICT', ondelete='SET NULL')
        batch_op.create_foreign_key('address_ibfk_3', 'equipment', ['equipment_id'], ['id'], onupdate='RESTRICT', ondelete='SET NULL')

    # ### end Alembic commands ###
