"""separate adresses

Revision ID: f91e5b604a0f
Revises: 03696ab890a8
Create Date: 2023-04-18 16:08:43.564312

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f91e5b604a0f'
down_revision = '03696ab890a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street', sa.String(length=2000), nullable=False),
    sa.Column('house', sa.String(length=200), nullable=False),
    sa.Column('building', sa.String(length=200), nullable=True),
    sa.Column('front_door', sa.String(length=200), nullable=True),
    sa.Column('apartment', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_column('apartment')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_address', ['address_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_ibfk_2', 'address', ['address_id'], ['id'])

    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apartment', mysql.VARCHAR(collation='utf8mb4_general_ci', length=200), nullable=True))

    op.drop_table('user_address')
    # ### end Alembic commands ###
