"""empty message

Revision ID: fd0acc5e133b
Revises: 3fb41e999c7b
Create Date: 2023-05-09 01:48:43.170225

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fd0acc5e133b'
down_revision = '3fb41e999c7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tariff_id', sa.Integer(), nullable=True))
        batch_op.alter_column('apartment',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=200),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'tariff', ['tariff_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('apartment',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=200),
               existing_nullable=False)
        batch_op.drop_column('tariff_id')

    # ### end Alembic commands ###
